apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod 
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:latest 
      envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-secret
      ports:
      - containerPort: 3306 
