apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdC1wYXNzd29yZA==  # base64 encoded 'root-password'
  MYSQL_USER: ZGJ1c2Vy                        # base64 encoded 'dbuser'
  MYSQL_PASSWORD: ZGJwYXNzd29yZA==            # base64 encoded 'dbpassword'
