apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secret
type: Opaque
data:
  PMA_HOST: bXlzcWwtc2VydmljZQ==            # base64 encoded 'mysql-service'
  PMA_USER: ZGJ1c2Vy                          # base64 encoded 'dbuser'
  PMA_PASSWORD: ZGJwYXNzd29yZA==              # base64 encoded 'dbpassword'




