apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30010
  type: NodePort
